layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
  - jekyll-sitemap
  
permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 4
  exclude:
    archived: false
    forks: false
    projects: 
     -  GetADelivery
    
social_media: 
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  instagram: gregorywalfish
  # keybase: your_username
  linkedin: gregorywalfish
  # mastodon: your_username
  medium: gregorywalfish
  # stackoverflow: your_user_id
  # telegram: your_username
  twitter: gregorywalfish
  # unsplash: your_username
  # vk: your_username
  # website: https://backdoormtl.com/
  # youtube: your_username

topics:
  - name: Backdoor MTL
    web_url: https://backdoormtl.com/
    image_url: https://user-images.githubusercontent.com/59707388/104234185-0afdef00-5421-11eb-9c87-b5f5cb91e530.png
  - name: Paysafe

  #- name: Sass
    web_url: https://www.paysafe.com/na-en/
    image_url: https://res-4.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_170,w_170,f_auto,b_white,q_auto:eco/txzyv21bswexrrzztlt9
